version: '3.8'

services:
  innotter_db:
    container_name: innotter_db
    image: postgres
    restart: always

    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      #POSTGRES_INITDB_ARGS
      #POSTGRES_INITDB_WALDIR
      #POSTGRES_HOST_AUTH_METHOD
      #PGDATA

    ports:
      - '3306:3306'


  innotter:
    container_name: innotter
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8000'
    depends_on:
      - innotter_db