# Generated by Django 4.0.6 on 2022-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0004_page_liked_posts_alter_page_follow_requests_and_more'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='followed_pages',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_pages', to='Page.page'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_pages',
            field=models.ManyToManyField(blank=True, null=True, related_name='requested_pages', to='Page.page'),
        ),
    ]
