# Generated by Django 4.0.6 on 2022-07-11 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Page', '0003_alter_page_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_posts', to='Post.post'),
        ),
        migrations.AlterField(
            model_name='page',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='follow_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Page.tag'),
        ),
    ]
