# Generated by Django 4.0.6 on 2022-07-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
    ]
