# Generated by Django 4.0.6 on 2022-07-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0004_page_liked_posts_alter_page_follow_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
